### ISSUE TITLE
BREAKING CHANGE: IDL contains 'reserved' identifier in dictionaries.

### ISSUE THREAD

**Issue by jpmedley** [w3c/webidl2.js#690]
Chrome IDL has [a dictionary](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/directive.idl) that breaks parsing. When you pass `parse()` the contents at the previous link webidl2 throws:

```AssertionError [ERR_ASSERTION]: Syntax error at line 9:
  DOMString toString
            ^ toString is a reserved identifier and must not be used.
```

cc: @marcoscaceres @sidvishnoi for ReSpec

**Comment by dontcallmedom** [comment]
the bug is in the WebIDL fragment rather than in the parser; the [source file for this fragment ](https://github.com/WICG/scroll-to-text-fragment/blob/dc18d43d72322b808655f3b6af2bdfed37364006/fragment-directive-api.md) annotates the `toString()` operation with `  // TODO: remove()?`.

(the right way would be use the [`stringifier` WebIDL keyword](https://webidl.spec.whatwg.org/#idl-stringifiers))
