### ISSUE TITLE
document white space

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#97]
We seem to be missing documentation for white space types... in particular, not sure what "ws-pea" and "ws-tpea" are (they sound cute tho 🥜 ).

**Comment by SaschaNaz** [comment]
The only documentation about pea is here...

https://github.com/w3c/webidl2.js/blob/649e457b788d09803d67d123cc9877cd0380b316/lib/webidl2.js#L106

tpea is being used on writer.js but the problem is that there is actually no tpea in webidl2.js.

https://github.com/w3c/webidl2.js/blob/bbbab23b3d717d65246a6a5d6cc70d1d81226721/lib/writer.js#L164-L170

**Comment by SaschaNaz** [comment]
https://github.com/w3c/webidl2.js/commit/a387b679ca80ce32004a1bc8eb2db3cef6c46e44 is the commit that removed tpea.

**Comment by marcoscaceres** [comment]
Ok, so it might be safe to just ignore it.

**Comment by SaschaNaz** [comment]
Or it may be a problem if we start maintaining writer.js. I don't know.

**Comment by saschanaz** [comment]
I think this can be closed now. Things that need more clarification can probably be discussed in #225.
